AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-layer-awscli
    Description: "Lambda Layer for AWS CLI"
    Author: Pahud Hsieh
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['layer','lambda','awscli','cli', 'aws', 'bash']
    HomePageUrl: https://github.com/aws-samples/aws-lambda-layer-awscli
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/aws-samples/aws-lambda-layer-awscli

Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Layer for awscli

Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}"
      ContentUri: ./layer.zip
      CompatibleRuntimes: 
        - provided
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain

Outputs:
  LayerVersionArn:
    Description: ARN for the published Layer version
    Value: !Ref LambdaLayer
    Export:
      Name: !Sub 'LayerVersionArn-${AWS::StackName}'
